"""Google search update history used by the /google-algorithm-updates/ page.

Timeline entries follow Search Engine Journal's "Google Algorithm Updates & Changes:
A Complete History" and the individual update articles it links to. All summaries are
written in our own words; every entry links back to the source article.
Entries marked ``extra=True`` are not on SEJ's list (which has no 2018-2021 entries) and
come from Google's own public announcements.
"""
from datetime import date

LAST_REVIEWED = date(2026, 9, 19)

SEJ = 'https://www.searchenginejournal.com/'
HISTORY_URL = SEJ + 'google-algorithm-history/'

# type key -> label, blurb (what this family of updates is about), what to do
TYPES = {
    'core': {
        'label': 'Core update',
        'blurb': 'Broad, periodic re-assessment of how Google’s ranking systems judge relevance and quality. There is no single thing to fix.',
        'todo': [
            'Wait until the rollout is finished, then compare Search Console data with the period before it started.',
            'Look at the pages that lost the most positions and ask whether they truly beat the pages now above them.',
            'Improve depth, originality and trust on those pages instead of making quick technical tweaks.',
            'Expect recovery, if it comes, to take weeks or months and to land with the next core update.',
        ],
    },
    'spam': {
        'label': 'Spam & policy',
        'blurb': 'Automated spam systems (SpamBrain) and written spam policies that demote or remove manipulative pages.',
        'todo': [
            'Re-read Google’s spam policies and check your site against each one.',
            'Remove scaled, auto-generated or doorway-style pages that exist mainly to rank.',
            'Secure the site: hacked pages can inject hidden spam without you noticing.',
            'If you were hit, fix the cause and allow months for automated systems to re-evaluate.',
        ],
    },
    'quality': {
        'label': 'Content quality',
        'blurb': 'Systems that reward original, useful, people-first content and demote thin, padded or search-engine-first pages.',
        'todo': [
            'Audit pages for real usefulness: does each one completely answer the searcher’s need?',
            'Add first-hand experience, original examples, data or photos that competitors cannot copy.',
            'Merge, rewrite or noindex thin and duplicate pages instead of leaving them live.',
            'Keep a clear site focus; avoid publishing on topics you have no experience in.',
        ],
    },
    'links': {
        'label': 'Link quality',
        'blurb': 'Updates that judge how links are earned, from early link-scheme filters to the real-time Penguin system.',
        'todo': [
            'Audit your backlink profile for paid, exchanged or obviously artificial links.',
            'Ask for removal of bad links first; use the disavow tool only as a last resort.',
            'Earn links with content and relationships people genuinely want to reference.',
            'Keep anchor text and link sources varied and natural.',
        ],
    },
    'local': {
        'label': 'Local search',
        'blurb': 'Changes to how location, proximity and web signals decide who appears for local intent.',
        'todo': [
            'Build unique pages for each location or service area, not swapped-city templates.',
            'Keep your name, address and phone details identical everywhere they appear.',
            'Claim and complete your Google Business Profile and collect genuine reviews.',
            'Strengthen your normal web authority: local rankings borrow from it.',
        ],
    },
    'ux': {
        'label': 'Page experience',
        'blurb': 'Signals about how pages feel to use: speed, stability, mobile-friendliness, security and ad clutter.',
        'todo': [
            'Serve every page over HTTPS and make it fully responsive on phones.',
            'Pass Core Web Vitals: fast main content, quick response to taps, no layout jumps.',
            'Keep ads, pop-ups and interstitials from covering the main content.',
            'Test regularly with PageSpeed Insights and Search Console reports.',
        ],
    },
    'reviews': {
        'label': 'Reviews',
        'blurb': 'Updates that reward reviews and comparisons backed by real, first-hand testing.',
        'todo': [
            'Show evidence of real use: original photos, measurements, test results.',
            'Explain benefits, drawbacks and who each option suits, not just manufacturer specs.',
            'Compare alternatives and say why you recommend one over another.',
            'Only publish reviews you or your team have genuinely tried.',
        ],
    },
    'ai': {
        'label': 'AI & search features',
        'blurb': 'AI summaries, Discover and other SERP features that change where clicks come from.',
        'todo': [
            'Answer questions directly and clearly, with well-structured headings and short answers.',
            'Make sure crawlers can access and render all important content.',
            'Track impressions and clicks per feature in Search Console, not just blue-link rankings.',
            'Build recognisable expertise and original content: it is what these systems prefer to cite.',
        ],
    },
    'infra': {
        'label': 'Understanding & indexing',
        'blurb': 'Infrastructure and language-understanding changes that help Google index faster and interpret meaning, not just keywords.',
        'todo': [
            'Write for the searcher’s intent and topic, not for exact-match keyword strings.',
            'Use clear structure, entities and structured data so meaning is unambiguous.',
            'Keep content current where the topic genuinely changes over time.',
            'Make sure important pages are crawlable and load quickly.',
        ],
    },
    'trust': {
        'label': 'Trust & authority',
        'blurb': 'Updates that favour trustworthy, established, expert sources, strongest on health, money and other high-stakes topics.',
        'todo': [
            'Show who is behind the content: named authors, credentials, an About page and real contact details.',
            'Cite sources and keep facts accurate; label opinion as opinion.',
            'Earn mentions and reviews from reputable third parties.',
            'Avoid keyword-stuffed domains and thin sites built only to rank.',
        ],
    },
}

_MONTHS = ['Jan', 'Feb', 'Mar', 'Apr', 'May', 'Jun', 'Jul', 'Aug', 'Sep', 'Oct', 'Nov', 'Dec']


def _d(s):
    if not s:
        return None
    y, m, d = (int(x) for x in s.split('-'))
    return date(y, m, d)


def _label(start, end, exact):
    if not exact:
        if end and end.year == start.year and end.month != start.month:
            return '%s–%s %d' % (_MONTHS[start.month - 1], _MONTHS[end.month - 1], start.year)
        return '%s %d' % (_MONTHS[start.month - 1], start.year)
    s = '%s %d' % (_MONTHS[start.month - 1], start.day)
    if not end:
        return '%s, %d' % (s, start.year)
    if end.year == start.year and end.month == start.month:
        return '%s–%d, %d' % (s, end.day, start.year)
    if end.year == start.year:
        return '%s – %s %d, %d' % (s, _MONTHS[end.month - 1], end.day, start.year)
    return '%s, %d – %s %d, %d' % (s, start.year, _MONTHS[end.month - 1], end.day, end.year)


# (slug, name, type, start, end, exact_dates, summary, affected, lesson, source, extra)
_RAW = [
    ('florida', 'Florida', 'links', '2003-11-16', None, True,
     'One of the first big spam clean-ups. Google began analysing link and anchor-text patterns, and rankings were shaken up just before the holiday shopping season.',
     'Many ordinary retailers and affiliates lost rankings overnight, along with the sites that had been over-optimised.',
     'Links have to look natural; patterns that look engineered eventually get noticed.',
     'google-algorithm-history/florida-update/', False),
    ('jagger', 'Jagger', 'links', '2005-09-01', '2005-11-30', False,
     'A multi-stage update aimed at low-quality link building.',
     'Sites relying on bought sitewide links, reciprocal exchanges with unrelated sites and link farms.',
     'Artificial link schemes were declared unwelcome long before Penguin.',
     'google-algorithm-history/jagger-update/', False),
    ('big-daddy', 'Big Daddy', 'infra', '2005-12-01', '2006-03-31', False,
     'An infrastructure overhaul that changed how Google handled URL canonicalisation and redirects, and filtered low-trust links.',
     'Sites with messy URLs, redirect chains, or link profiles built on paid and reciprocal links.',
     'Clean site architecture and trustworthy links help crawling as well as ranking.',
     'google-algorithm-history/big-daddy-update/', False),
    ('vince', 'Vince', 'trust', '2009-01-18', None, True,
     'Established brands started to win more of the broad, competitive queries.',
     'Smaller affiliate and resource sites that had ranked on aggressive optimisation alone.',
     'Brand trust and a real online presence began to outweigh pure SEO tricks.',
     'google-algorithm-history/vince-update/', False),
    ('caffeine', 'Caffeine', 'infra', '2010-06-08', None, True,
     'A rebuilt indexing system (announced August 2009, live June 2010) that let Google crawl and store content far more quickly, giving noticeably fresher results.',
     'Not a penalty: it levelled the field for fresh content and made future features possible.',
     'Fast indexing rewards sites that publish and update regularly.',
     'google-algorithm-history/caffeine-update/', False),
    ('panda', 'Panda', 'quality', '2011-02-23', None, True,
     'A quality filter aimed at content farms and thin, duplicated or ad-stuffed pages. It ran as a separate filter for years and was folded into the core ranking algorithm in January 2016.',
     'Sites with shallow, unoriginal content, inflated word counts, excessive ads and weak editorial standards.',
     'Quality is judged across a whole site, so weak pages can drag good ones down.',
     'google-algorithm-history/panda-update/', False),
    ('freshness', 'Freshness algorithm', 'infra', '2011-11-03', None, True,
     'Made recency a ranking factor for queries that deserve up-to-date answers such as news, recurring events and fast-changing topics, roughly a third of searches.',
     'Sites that were slow to publish on time-sensitive topics.',
     'Update content where the topic genuinely changes; do not fake dates on evergreen pages.',
     'google-algorithm-history/freshness-algorithm/', False),
    ('page-layout', 'Page Layout algorithm', 'ux', '2012-01-01', None, False,
     'Started demoting pages that crammed ads above the fold so visitors had to scroll to reach the actual content; refreshed several times up to 2016.',
     'Ad-heavy sites that put monetisation ahead of the visitor.',
     'Let people see real content immediately.',
     'google-algorithm-history/page-layout/', False),
    ('venice', 'Venice', 'local', '2012-02-01', None, False,
     'Brought local intent into ordinary organic results, so location-relevant pages could surface even without a Places listing.',
     'Local businesses gained visibility against big national brands.',
     'Location-specific pages became a real ranking asset.',
     'google-algorithm-history/venice/', False),
    ('penguin', 'Penguin', 'links', '2012-04-24', None, False,
     'A webspam update aimed at manipulative link building. It went through several refreshes and became part of the core algorithm, running in real time, in September 2016 (Penguin 4.0), when it shifted from penalising to devaluing bad links.',
     'Sites with paid links, link exchanges, keyword-stuffed anchors and other unnatural link patterns.',
     'Earn links; do not manufacture them.',
     'google-algorithm-history/penguin-update/', False),
    ('emd', 'EMD (Exact Match Domain)', 'trust', '2012-09-28', None, True,
     'Reduced the ranking advantage of keyword-in-domain sites that had little quality content behind them.',
     'Low-quality exact-match domains, not every domain that happened to contain a keyword.',
     'A keyword domain cannot stand in for real content and authority.',
     'google-algorithm-history/emd-update/', False),
    ('payday-loan', 'Payday Loan update', 'spam', '2013-06-11', '2014-06-30', False,
     'A series of updates (versions 1.0–3.0) aimed at spammy queries and sites in high-risk niches such as loans, gambling, pharmaceuticals and adult content.',
     'Sites in spam-prone industries using paid links, keyword stuffing and generated content.',
     'Your site has to be worthy of ranking on its merits.',
     'google-algorithm-history/payday-loan-update/', False),
    ('hummingbird', 'Hummingbird', 'infra', '2013-08-15', None, False,
     'A rewrite of Google’s core search algorithm (live in August, announced in September 2013) so it could understand what a query means, especially conversational ones, rather than matching words one by one.',
     'Sites that relied on thousands of near-identical long-tail keyword variations lost their edge; most quality sites barely noticed.',
     'Write about topics and intent, not keyword permutations.',
     'google-algorithm-history/hummingbird-update/', False),
    ('pigeon', 'Pigeon', 'local', '2014-07-24', None, True,
     'Tied local results more closely to standard web-ranking signals and shrank the local pack to about three listings.',
     'Local businesses with a thin web presence relying only on their listing.',
     'Local SEO needs real website authority, not just a profile.',
     'google-algorithm-history/pigeon-update/', False),
    ('mobilegeddon', 'Mobilegeddon (mobile-friendly update)', 'ux', '2015-04-21', None, True,
     'A mobile-friendliness ranking signal for mobile searches, announced in February 2015 and strengthened in May 2016. It set the stage for mobile-first indexing.',
     'Pages that were not usable on phones lost visibility in mobile results.',
     'Design for phones first.',
     'google-algorithm-history/mobile-friendly-update/', False),
    ('quality-updates', 'Quality updates (Phantom)', 'quality', '2015-05-01', None, False,
     'Unannounced quality changes starting May 2015, with further waves in 2016 and 2017, targeting thin content, clickbait and intrusive ads.',
     'Content farms, clickbait pages, and user-generated sites without quality controls.',
     'Audit your site as a visitor would and fix what annoys them.',
     'google-algorithm-history/quality-update/', False),
    ('rankbrain', 'RankBrain', 'infra', '2015-10-26', None, True,
     'A machine-learning system, announced in October 2015 (live earlier that year), that helps interpret unfamiliar queries by understanding entities and intent, not just literal words.',
     'It affects how results are matched to queries in general rather than penalising sites.',
     'Serve user intent and make entities and context clear.',
     'google-algorithm-history/rankbrain/', False),
    ('fred', 'Fred', 'quality', '2017-03-07', None, True,
     'Hit low-value sites, often affiliate-driven, that paired thin content with heavy advertising and interstitials.',
     'Pages where ads outweigh the useful content, or that use deceptive ad placements.',
     'Align with the quality rater guidelines (expertise, authoritativeness, trust) and reduce ad clutter.',
     'google-algorithm-history/fred-update/', False),
    ('medic', 'Medic core update', 'trust', '2018-08-01', None, True,
     'A broad core update that had an especially visible effect on health, medical and other “your money or your life” sites, and pushed expertise, authority and trust (E-A-T, now E-E-A-T) into the spotlight.',
     'Sites giving high-stakes advice without clear expertise or trust signals.',
     'On sensitive topics, show who is behind the advice and why they can be trusted.',
     None, True),
    ('bert', 'BERT', 'infra', '2019-10-25', None, True,
     'A language-understanding model that helps Google interpret the context and relationships between words, which matters most for longer, conversational queries.',
     'Not a penalty; it improves matching of queries to pages that answer them naturally.',
     'Write clearly and naturally for the question being asked.',
     None, True),
    ('page-experience-mobile', 'Page experience update (mobile)', 'ux', '2021-06-15', '2021-09-02', False,
     'Rolled Core Web Vitals, HTTPS and the absence of intrusive interstitials into ranking signals for mobile search.',
     'Slow, unstable or insecure pages.',
     'Speed, stability and security are ranking hygiene.',
     None, True),
    ('page-experience-desktop', 'Page Experience update (desktop)', 'ux', '2022-02-22', '2022-03-31', False,
     'Extended page-experience signals to desktop search over about five weeks: Core Web Vitals, HTTPS and no intrusive interstitials (mobile-friendliness is not part of the desktop signal).',
     'Desktop pages with poor loading, responsiveness or stability.',
     'Use the Page Experience report in Search Console and fix the slow pages first.',
     'google-page-experience-update-for-desktop-starts-rolling-out/439191/', False),
    ('product-reviews-mar-2022', 'March 2022 product reviews update', 'reviews', '2022-03-23', None, True,
     'Improved recognition of high-quality product reviews across several weeks: first-hand usage, original photos and audio, and comparisons beyond the manufacturer’s claims.',
     'Reviews that summarised other sources without real testing.',
     'Prove you used the product, and explain who it suits and why.',
     'google-launches-third-product-review-algorithm-update/442947/', False),
    ('core-may-2022', 'May 2022 core update', 'core', '2022-05-22', '2022-06-09', True,
     'A broad core update refreshing how Google’s ranking systems assess relevance and quality.',
     'All industries and content types; effects varied widely between sites.',
     'Judge success against your pre-update baseline once the rollout ends.',
     'google-may-2022-broad-core-algorithm-update/451783/', False),
    ('product-reviews-jul-2022', 'July 2022 product reviews update', 'reviews', '2022-07-27', '2022-08-02', True,
     'Refined how product reviews are ranked, especially for e-commerce and affiliate publishers.',
     'Review content lacking evidence of first-hand experience.',
     'Depth and original evidence beat volume.',
     'google-july-2022-product-review-algorithm-update-rolling-out-now/459209/', False),
    ('helpful-content-aug-2022', 'Helpful Content Update', 'quality', '2022-08-25', '2022-09-09', True,
     'Introduced a site-wide, machine-learning signal that rewards people-first content and demotes pages written mainly to attract search traffic. It began with English-language results and expanded later.',
     'Writers covering topics outside their expertise, clickbait, padded pages and content chosen only because it might attract traffic.',
     'Create content for your audience first; be honest about what you know.',
     'googles-helpful-content-update-rolls-out-7-things-to-know/462610/', False),
    ('core-sep-2022', 'September 2022 core update', 'core', '2022-09-12', '2022-09-26', True,
     'A broad core update that reshuffled results worldwide.',
     'Sites of all kinds; no single target.',
     'Improve overall content quality rather than chasing one signal.',
     'google-announces-september-2022-core-algorithm-update/464195/', False),
    ('product-reviews-sep-2022', 'September 2022 product review update', 'reviews', '2022-09-20', '2022-09-26', True,
     'A further round of improving how high-quality product reviews are identified.',
     'Thin or affiliate-only product pages.',
     'Keep adding first-hand detail and comparisons.',
     'google-september-2022-product-review-algorithm-update/465021/', False),
    ('spam-oct-2022', 'October 2022 spam update', 'spam', '2022-10-19', '2022-10-21', True,
     'A worldwide spam update improving the automated systems that detect deceptive, malware-spreading and phishing pages.',
     'Spam sites and sites hacked to serve hidden spam.',
     'Follow Google Search Essentials and keep your site secure.',
     'google-spam-algorithm-update-rolling-out-now/468297/', False),
    ('helpful-content-dec-2022', 'December 2022 helpful content update', 'quality', '2022-12-05', '2023-01-12', True,
     'Expanded the helpful content system to all languages and refined it.',
     'Unhelpful, search-first content in every language.',
     'People-first content standards apply everywhere.',
     'google-rolls-out-december-2022-helpful-content-update/473360/', False),
    ('link-spam-dec-2022', 'December 2022 link spam update', 'links', '2022-12-14', '2023-01-12, ', True,
     'Used SpamBrain to detect and neutralise unnatural links, both spammy links pointing to sites and links sold or placed to pass ranking credit.',
     'Sites whose rankings depended on artificial links, which lost that value.',
     'Links that were never earned stop counting.',
     'google-december-2022-link-spam-update/474233/', False),
    ('product-reviews-feb-2023', 'February 2023 product reviews update', 'reviews', '2023-02-21', '2023-03-18', True,
     'Broadened the product review system to more languages worldwide.',
     'Review content in additional languages with little first-hand evidence.',
     'Show real testing in every language you publish.',
     'google-february-2023-product-reviews-update/480580/', False),
    ('core-mar-2023', 'March 2023 core update', 'core', '2023-03-15', '2023-03-28', True,
     'A broad core update affecting search relevance globally.',
     'No specific type of site.',
     'Compare against your baseline and improve weak pages.',
     'google-rolls-out-march-2023-core-algorithm-update/482389/', False),
    ('reviews-apr-2023', 'April 2023 reviews update', 'reviews', '2023-04-12', '2023-04-25', True,
     'Extended the review system beyond products to services, places and more, judging reviews at page level for quality and experience.',
     'Reviews of services, films, apps and businesses without genuine experience behind them.',
     'The evidence standard now covers all review content.',
     'google-april-2023-reviews-update/484503/', False),
    ('core-aug-2023', 'August 2023 core update', 'core', '2023-08-22', '2023-09-07', True,
     'A broad core update refreshing ranking systems worldwide.',
     'Wide-ranging, no single target.',
     'Keep quality high everywhere, not just on your best pages.',
     'google-launches-august-2023-core-update/494473/', False),
    ('helpful-content-sep-2023', 'September 2023 helpful content update', 'quality', '2023-09-14', '2023-09-28', True,
     'Refined how the helpful content system identifies and ranks people-first content.',
     'Sites with unhelpful content mixed in with the good.',
     'Prune or improve pages that add nothing.',
     'google-september-2023-helpful-content-update-changes-to-the-algorithm/496454/', False),
    ('spam-oct-2023', 'October 2023 spam update', 'spam', '2023-10-04', '2023-10-19', True,
     'Improved spam detection worldwide and in more languages via SpamBrain.',
     'Cloaking, hacked, auto-generated and expired-domain spam.',
     'Stay clear of manipulative tactics in any language.',
     'google-rolls-out-october-2023-spam-update/497794/', False),
    ('core-oct-2023', 'October 2023 core update', 'core', '2023-10-05', '2023-10-19', True,
     'A broad core update that overlapped with the October spam update.',
     'General search results worldwide.',
     'Separate spam effects from core effects when analysing traffic.',
     'google-launches-october-2023-core-algorithm-update/497904/', False),
    ('reviews-nov-2023', 'November 2023 reviews update', 'reviews', '2023-11-08', '2023-12-07, ', True,
     'Another page-level pass over review content to reward high-quality, experience-based assessments.',
     'Low-effort review pages.',
     'Reviews need real substance to compete.',
     'google-rolls-out-november-2023-reviews-update/500795/', False),
    ('core-nov-2023', 'November 2023 core update', 'core', '2023-11-02', '2023-11-28', True,
     'The fourth core update of 2023, refreshing overall relevance.',
     'Broad, varied effects.',
     'Sustained quality improvement beats reacting to each update.',
     'google-rolls-out-november-2023-core-update/500009/', False),
    ('spam-mar-2024', 'March 2024 spam update', 'spam', '2024-03-05', None, False,
     'A spam update launched alongside the March core update, backing new spam policies against manipulative tactics.',
     'Scaled content abuse, site reputation abuse and expired-domain abuse.',
     'Read the new spam policies and audit your site against them.',
     'google-completes-march-spam-update-core-update-continues/511655/', False),
    ('core-mar-2024', 'March 2024 core update', 'core', '2024-03-05', '2024-04-19', True,
     'A major change: helpful-content signals were folded into the core ranking systems, and Google said it expected to cut unhelpful, unoriginal results by around 40%. It came with three new spam policies (scaled content abuse, site reputation abuse, expired domain abuse).',
     'Mass-produced content, third-party content hosted to borrow a site’s reputation, and repurposed expired domains.',
     'Original, useful content is now judged inside the core system itself.',
     'google-march-2024-core-update/510243/', False),
    ('site-reputation-abuse-may-2024', 'Site reputation abuse enforcement', 'spam', '2024-05-06', None, True,
     'Google started manual actions against “parasite SEO”: third-party pages published on an established site with little or no first-party oversight, purely to manipulate rankings.',
     'Publishers hosting outsourced product-review or coupon sections that lacked original evidence and real involvement.',
     'You are responsible for everything published under your domain.',
     'google-confirms-site-reputation-abuse-update/515584/', False),
    ('ai-overviews', 'AI Overviews', 'ai', '2024-05-14', None, True,
     'Google launched AI-generated summaries in U.S. Search, powered by a Gemini model, later expanded to more countries. They answer questions directly and change where clicks come from.',
     'Publishers whose pages answer simple questions that a summary can now cover.',
     'Structure content around clear questions and answers, and build original expertise worth citing.',
     'google-rolls-out-sge-ai-powered-overviews/516279/', False),
    ('spam-jun-2024', 'June 2024 spam update', 'spam', '2024-06-20', '2024-06-26', True,
     'A spam update across multiple languages that targeted spam and low-quality search content.',
     'Pages breaking spam policies.',
     'Keep policy compliance a permanent habit.',
     'google-launches-june-2024-spam-update/520281/', False),
    ('explicit-fake-content-jul-2024', 'Explicit fake content update', 'spam', '2024-07-31', None, True,
     'A change to demote non-consensual explicit imagery, including AI-generated deepfakes, and make removal requests easier.',
     'Sites publishing or distributing this material.',
     'Synthetic-content policies are strict and enforced.',
     'google-search-algorithm-update-targeting-explicit-deepfakes/523478/', False),
    ('core-aug-2024', 'August 2024 core update', 'core', '2024-08-15', '2024-09-03', True,
     'A core update that promoted high-quality, people-first content and demoted low-value SEO-first content.',
     'Sites with content made mainly to rank.',
     'Original value is the safest ranking strategy.',
     'google-rolls-out-august-2024-core-update/524529/', False),
    ('core-nov-2024', 'November 2024 core update', 'core', '2024-11-11', '2024-12-05', True,
     'A routine core refinement rolled out over about three weeks; effects were moderate and varied by site and sector. Google’s advice: wait for completion, compare before and after, and improve quality sustainably.',
     'Some sites saw drops; many did not notice.',
     'Do not react mid-rollout; analyse afterwards.',
     'google-rolls-out-november-2024-core-algorithm-update/532364/', False),
    ('site-reputation-abuse-policy-nov-2024', 'Site reputation abuse policy update', 'spam', '2024-11-19', None, True,
     'Google tightened its site reputation abuse policy and clarified enforcement, with manual actions in place and algorithmic detection planned.',
     'Sites hosting third-party content mainly to exploit their ranking power.',
     'Even close partnerships must have genuine first-party oversight.',
     'google-strengthens-policy-against-site-reputation-abuse/533018/', False),
    ('core-dec-2024', 'December 2024 core update', 'core', '2024-12-12', '2024-12-18', True,
     'A short core update that followed closely after the November one.',
     'Broad, mixed effects.',
     'Wait for stability before drawing conclusions.',
     'google-rolls-out-december-2024-core-update/535214/', False),
    ('spam-dec-2024', 'December 2024 spam update', 'spam', '2024-12-19', '2024-12-26', True,
     'The last spam update of 2024, run across search results.',
     'Spam and low-quality content.',
     'Regular compliance checks pay off.',
     'google-launches-final-spam-update-of-the-year/535963/', False),
    ('core-mar-2025', 'March 2025 core update', 'core', '2025-03-13', '2025-03-27, ', True,
     'A broad core update applied globally.',
     'General results worldwide.',
     'Measure against your baseline, then improve weak pages.',
     'google-begins-rolling-out-march-core-algorithm-update/541981/', False),
    ('core-jun-2025', 'June 2025 core update', 'core', '2025-06-30', '2025-07-17', True,
     'A broad core update across languages, announced without detailed commentary. Google’s aim: surface more relevant, satisfying content.',
     'Every industry and content type, effects immediate or gradual.',
     'Avoid drastic reactive changes unless you find a specific problem.',
     'google-rolls-out-june-2025-core-update/550161/', False),
    ('spam-aug-2025', 'August 2025 spam update', 'spam', '2025-08-26', '2025-09-21', True,
     'A slow spam rollout that took 26 days. Google gave no details about which tactics it targeted, only that sites should stay aligned with its spam policies.',
     'Sites near or over the line on spam policies.',
     'Do not make panic changes during a rollout; compare data afterwards.',
     'google-rolls-out-august-spam-update-targeting-search-quality/554611/', False),
    ('discover-core-feb-2026', 'February 2026 Discover core update', 'ai', '2026-02-05', '2026-02-19', True,
     'A core update for the Discover feed only: it favours locally relevant content from sites in the reader’s country, cuts sensational or clickbait pages, and lifts in-depth, original, timely content from sites with expertise.',
     'Publishers dependent on Discover traffic, particularly with clickbait or off-topic content.',
     'Track Discover separately from search; build recognised expertise.',
     'google-releases-core-update-targeting-discover-feed/566647/', False),
    ('spam-mar-2026', 'March 2026 spam update', 'spam', '2026-03-24', '2026-03-25', True,
     'A very fast spam update that finished in under a day and appeared to have a muted impact.',
     'Sites breaking spam policies.',
     'Even short spam updates are worth checking against.',
     'google-begins-rolling-out-the-march-2026-spam-update/570428/', False),
    ('core-mar-2026', 'March 2026 core update', 'core', '2026-03-27', '2026-04-08', True,
     'The first broad core update of 2026, with no announced goals beyond surfacing relevant, satisfying content. Drops do not signal a policy violation, they reflect a wider re-assessment of quality.',
     'Wide-ranging, no single target.',
     'Wait a full week after the rollout ends before analysing Search Console.',
     'google-begins-rolling-out-march-2026-core-update/570657/', False),
    ('core-may-2026', 'May 2026 core update', 'core', '2026-05-21', '2026-06-02', True,
     'The second core update of 2026, released with only a short notice and no companion blog post. Google’s stated aim matches earlier core updates.',
     'All industries, no announced target.',
     'Use pre-May 21 performance as your baseline and avoid content changes during the rollout.',
     'google-begins-rolling-out-may-2026-core-update/575589/', False),
    ('spam-jun-2026', 'June 2026 spam update', 'spam', '2026-06-24', '2026-06-26', True,
     'A short global spam update targeting spam and low-quality search content.',
     'Sites using manipulative tactics.',
     'Keep policy compliance continuous.',
     'google-begins-rolling-out-the-june-2026-spam-update/580424/', False),
    ('spam-aug-2026', 'August 2026 spam update', 'spam', '2026-08-18', '2026-08-21, ', True,
     'The third spam update of 2026, applied globally in about two days and 16 hours. Google announced no new policies, though its spam policies now explicitly cover attempts to manipulate generative-AI answers. Recovery can take months.',
     'Sites breaking existing spam policies, including manipulation aimed at AI answers.',
     'Do not try to game AI answers; earn citations with genuine expertise.',
     'google-begins-rolling-out-the-august-2026-spam-update/586301/', False),
]


def _clean_date(s):
    return s.strip().rstrip(',').strip() if s else None


def build_updates():
    """Return update dicts, newest first, with computed display fields."""
    out = []
    for (slug, name, typ, start, end, exact, summary, affected, lesson, src, extra) in _RAW:
        s, e = _d(_clean_date(start)), _d(_clean_date(end))
        out.append({
            'slug': slug,
            'name': name,
            'type': typ,
            'type_label': TYPES[typ]['label'],
            'start': s,
            'end': e,
            'year': s.year,
            'ts': s.strftime('%Y%m%d'),
            'when': _label(s, e, exact),
            'summary': summary,
            'affected': affected,
            'lesson': lesson,
            'todo': TYPES[typ]['todo'],
            'source': (SEJ + src) if src else None,
            'extra': extra,
        })
    out.sort(key=lambda u: u['ts'], reverse=True)
    return out


def year_counts(updates):
    counts = {}
    for u in updates:
        counts[u['year']] = counts.get(u['year'], 0) + 1
    top = max(counts.values())
    return [{'year': y, 'count': counts[y], 'pct': round(counts[y] / top * 100)} for y in sorted(counts)]


CHECKLIST = [
    ('Helpful, people-first content', 'quality', [
        ('c1', 'Every important page fully answers the visitor’s question, so nobody has to go back to search.', 'Helpful Content, core updates'),
        ('c2', 'Pages contain first-hand experience, original examples, data or images, not just rewritten summaries.', 'Helpful Content, reviews updates'),
        ('c3', 'The site has a clear focus and we only write about topics we genuinely know.', 'Helpful Content'),
        ('c4', 'There are no mass-produced or auto-generated pages that exist mainly to catch searches.', 'Spam policies, March 2024 core'),
    ]),
    ('Trust & E-E-A-T', 'trust', [
        ('c5', 'Content shows who wrote it (named authors with a short bio) and who runs the business.', 'Medic, Fred, quality guidelines'),
        ('c6', 'About and Contact pages give real details: business name, location, way to reach a person.', 'Vince, Medic'),
        ('c7', 'Claims are sourced, facts are checked, and testimonials or reviews are genuine.', 'Reviews updates, Medic'),
    ]),
    ('Technical & page experience', 'ux', [
        ('c8', 'The whole site runs on HTTPS and works properly on phones.', 'Mobilegeddon, Page Experience'),
        ('c9', 'Core Web Vitals pass: fast main content, quick response to taps, no layout jumps.', 'Page Experience'),
        ('c10', 'No intrusive pop-ups or ad clutter push the real content out of view.', 'Page Layout, Fred'),
        ('c11', 'Important content is crawlable and renders without needing a click or login.', 'Caffeine, AI Overviews'),
    ]),
    ('Links & spam safety', 'links', [
        ('c12', 'Links are earned through content and relationships; none are bought or exchanged at scale.', 'Penguin, Link spam updates'),
        ('c13', 'Any third-party or guest content on our domain is reviewed and edited by us.', 'Site reputation abuse'),
        ('c14', 'The site is secure and monitored, so hidden spam pages cannot be injected.', 'Spam updates'),
    ]),
    ('Local & AI-ready', 'local', [
        ('c15', 'Each location or service area has a genuinely unique page, with consistent name, address and phone.', 'Venice, Pigeon'),
        ('c16', 'Key pages answer common questions directly, use clear headings and structured data.', 'RankBrain, AI Overviews'),
    ]),
]

FINDER = [
    ('q_reviews', 'We publish reviews or comparisons of products, services or places.', ['reviews', 'quality']),
    ('q_scale', 'We publish lots of pages quickly, or use AI or templates to produce content at scale.', ['quality', 'spam']),
    ('q_third', 'Other people or partners publish pages, coupons or sections on our domain.', ['spam']),
    ('q_links', 'We buy links, swap links or do large-scale guest posting.', ['links', 'spam']),
    ('q_local', 'We serve customers in a specific city or region.', ['local']),
    ('q_ymyl', 'We give health, money, legal or other high-stakes advice.', ['trust', 'core']),
    ('q_ads', 'Our pages carry heavy ads, pop-ups or interstitials, or load slowly.', ['ux', 'quality']),
    ('q_discover', 'We depend on Google Discover, news or trending-topic traffic.', ['ai', 'quality']),
    ('q_ai', 'We want to appear in AI answers and summaries.', ['ai', 'infra']),
]

CORE_STEPS = [
    ('Announced', 'Google posts a short notice on the Search Status Dashboard. Recent core updates have often come without a companion blog post or stated goals.'),
    ('Rolling out', 'Rollouts usually run one to three weeks, and rankings move around while they do. Changing your site mid-rollout muddies the data.'),
    ('Completed', 'Google marks the update complete on the dashboard. Wait about a week after that before analysing anything.'),
    ('Measure', 'Compare Search Console performance with the period before the update began. Focus on pages that lost the most positions.'),
    ('Improve', 'Ask honestly whether those pages deserve to rank. Improve depth, originality and trust. Recovery is gradual and often lands with a later core update.'),
]

SELF_ASSESSMENT = [
    'Does the content provide original information, reporting, research or analysis?',
    'Does it give a substantial, complete and comprehensive description of the topic?',
    'Would you trust it, and does it show who created it and why?',
    'Would someone reading it feel they learned enough to reach their goal?',
    'Is it written by someone with real, demonstrable knowledge of the subject?',
    'Does the page avoid excessive ads, pop-ups and clutter that distract from the content?',
    'Was it made mainly to help people, rather than to attract search engine traffic?',
    'Is it something you would bookmark, share with a friend or recommend?',
]

PLAYBOOK = [
    ('If you were hit by a core update', 'Do not panic and do not rewrite everything at once.',
     ['Confirm timing: check your traffic drop against the dates in the timeline, and make sure the rollout has finished.',
      'Segment in Search Console by page, query and country to see whether the drop is site-wide or concentrated.',
      'Review the top pages that lost ground with fresh eyes: compare each against the pages now ranking above it.',
      'Prioritise substantive improvements: depth, originality, first-hand experience, clearer authorship and sourcing.',
      'Fix technical problems you find, but do not expect technical tweaks alone to reverse a quality re-assessment.',
      'Track progress over months; the next core update is when improvements are usually reassessed.']),
    ('If you were hit by a spam update', 'Spam actions are about policy violations, so the fix is specific.',
     ['Read the current spam policies and list any tactic on your site that matches.',
      'Remove scaled, auto-generated, doorway, hidden or manipulative content and links.',
      'Check for hacked pages or injected links with a security scan and Search Console’s security report.',
      'Recovery can take months because the automated systems need time to see the change.']),
    ('If you hosted third-party content', 'Site reputation abuse is judged on oversight, not on who wrote the words.',
     ['Audit every section written by partners, sponsors or guests.',
      'Add real editorial review or remove the section.',
      'Noindex pages that exist only to borrow your domain’s ranking power.']),
    ('If you rely on AI answers or Discover', 'These features reward citeable, original, expert content.',
     ['Structure pages so key questions have short, direct answers followed by depth.',
      'Build topical depth and clear author expertise.',
      'Monitor Discover and search separately in Search Console.']),
]

FAQ = [
    ('What is a Google core update?',
     'A core update is a broad change to Google’s main ranking systems, released several times a year. It is not aimed at a specific tactic or site type. It re-assesses how content is judged for relevance and quality across the whole web, so results shift for many sites.'),
    ('How is a core update different from a spam update?',
     'A core update reassesses quality and relevance in general, so a drop does not mean you broke a rule. A spam update targets policy violations, such as scaled content, link schemes or hidden spam, and recovery depends on fixing the specific violation.'),
    ('How long does a core update take to roll out?',
     'Google typically says a core update may take up to two weeks. Some finish faster and some run for several weeks. Wait until Google marks it complete and then a further week before analysing your data.'),
    ('Should I change my site while an update is rolling out?',
     'Usually no. Rankings move around during a rollout, and changing content at the same time makes it hard to know what caused what. Wait until it finishes, compare with your baseline, then improve.'),
    ('How do I recover from a core update drop?',
     'There is no quick fix. Improve the quality, depth, originality and trustworthiness of the pages that lost visibility, and make it clear who created the content. Improvements are typically reassessed over weeks or months, often with a later core update.'),
    ('What is E-E-A-T and is it a ranking factor?',
     'E-E-A-T stands for experience, expertise, authoritativeness and trust. It comes from Google’s quality rater guidelines and describes what good content looks like. It is not a single score, but many ranking signals aim to reward pages that demonstrate it.'),
    ('How do I make a site resilient to Google updates?',
     'Build for the visitor: satisfy search intent completely, show real experience and clear authorship, keep the site fast and secure, earn links naturally, avoid scaled or manipulative content, and monitor Search Console so you can spot trends early.'),
]
