# Generated by Django 5.1.2 on 2025-01-01 04:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GetTouchWithUs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=500)),
                ('email', models.EmailField(max_length=500)),
                ('phone_number', models.CharField(max_length=500)),
                ('company_name', models.CharField(max_length=500)),
                ('website_url', models.URLField(blank=True, max_length=500, null=True)),
                ('select_service', models.CharField(choices=[('seo', 'Search Engine Optimization'), ('google_local', 'Google Local Listing'), ('adwords', 'Google Adwords'), ('web_design', 'Website Design & Development'), ('wordpress', 'WordPress Website'), ('ecommerce', 'eCommerce Website'), ('social_media', 'Social Media Marketing'), ('facebook_ads', 'Facebook Ads'), ('youtube_ads', 'YouTube Ads'), ('others', 'Others')], max_length=500)),
                ('added_date_time', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
