# Generated by Django 5.1.2 on 2025-02-11 04:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='gettouchwithus',
            options={'verbose_name': 'Get in Touch', 'verbose_name_plural': 'Get in Touch'},
        ),
        migrations.AlterField(
            model_name='gettouchwithus',
            name='select_service',
            field=models.CharField(blank=True, choices=[('seo', 'Search Engine Optimization'), ('google_local', 'Google Local Listing'), ('adwords', 'Google Adwords'), ('web_design', 'Website Design & Development'), ('wordpress', 'WordPress Website'), ('ecommerce', 'eCommerce Website'), ('social_media', 'Social Media Marketing'), ('facebook_ads', 'Facebook Ads'), ('youtube_ads', 'YouTube Ads'), ('others', 'Others')], max_length=500, null=True),
        ),
    ]
