# Generated by Django 6.1.1 on 2026-09-14 07:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_app', '0002_alter_gettouchwithus_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='gettouchwithus',
            name='message',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='gettouchwithus',
            name='subject',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='gettouchwithus',
            name='company_name',
            field=models.CharField(blank=True, max_length=500),
        ),
    ]
