# Generated by Django 6.1.1 on 2026-09-19 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SiteSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(blank=True, help_text='Shown in the header, footer, contact page and structured data, e.g. +919812345678', max_length=40)),
                ('email', models.EmailField(blank=True, help_text='Public contact email', max_length=254)),
                ('address', models.CharField(blank=True, help_text='Public address line shown in the footer and contact page', max_length=250)),
                ('facebook', models.URLField(blank=True)),
                ('twitter', models.URLField(blank=True, verbose_name='X / Twitter')),
                ('youtube', models.URLField(blank=True)),
                ('instagram', models.URLField(blank=True)),
                ('linkedin', models.URLField(blank=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Site settings',
                'verbose_name_plural': 'Site settings',
            },
        ),
    ]
