# Generated by Django 6.1.1 on 2026-09-14 10:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_blogpost_locationpage'),
    ]

    operations = [
        migrations.CreateModel(
            name='CaseStudy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client_name', models.CharField(max_length=150)),
                ('slug', models.SlugField(max_length=200, unique=True)),
                ('industry', models.CharField(blank=True, max_length=120)),
                ('summary', models.TextField(help_text='One or two sentence result-focused summary, e.g. "Increased organic traffic by 52% in 6 months."', max_length=500)),
                ('challenge', models.TextField(help_text='What problem was the client facing?')),
                ('solution', models.TextField(help_text='What did Rizen Digital do?')),
                ('results', models.TextField(help_text='What outcome did the client get?')),
                ('metric_1_value', models.CharField(blank=True, help_text='e.g. "52%"', max_length=20)),
                ('metric_1_label', models.CharField(blank=True, help_text='e.g. "Organic traffic increase"', max_length=60)),
                ('metric_2_value', models.CharField(blank=True, max_length=20)),
                ('metric_2_label', models.CharField(blank=True, max_length=60)),
                ('metric_3_value', models.CharField(blank=True, max_length=20)),
                ('metric_3_label', models.CharField(blank=True, max_length=60)),
                ('testimonial', models.TextField(blank=True)),
                ('testimonial_author', models.CharField(blank=True, max_length=120)),
                ('featured_image', models.FileField(blank=True, upload_to='case-studies/')),
                ('meta_title', models.CharField(blank=True, max_length=60)),
                ('meta_description', models.CharField(blank=True, max_length=160)),
                ('is_published', models.BooleanField(default=False)),
                ('published_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('service', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='case_studies', to='home.service')),
            ],
            options={
                'verbose_name': 'Case study',
                'verbose_name_plural': 'Case studies',
                'ordering': ('-published_at', '-created_at'),
            },
        ),
    ]
