# Generated by Django 6.1.1 on 2026-09-17 11:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_casestudy'),
    ]

    operations = [
        migrations.AddField(
            model_name='locationpage',
            name='country',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name='locationpage',
            name='latitude',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True),
        ),
        migrations.AddField(
            model_name='locationpage',
            name='longitude',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True),
        ),
        migrations.AddField(
            model_name='locationpage',
            name='map_embed_url',
            field=models.URLField(blank=True, help_text='Google Maps embed URL (src of an <iframe>).'),
        ),
        migrations.CreateModel(
            name='LocationFAQ',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=200)),
                ('answer', models.TextField(max_length=600)),
                ('order', models.PositiveIntegerField(default=0)),
                ('location_page', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='faqs', to='home.locationpage')),
            ],
            options={
                'verbose_name': 'Location FAQ',
                'verbose_name_plural': 'Location FAQs',
                'ordering': ('order', 'id'),
            },
        ),
    ]
