# Generated by Django 6.1.1 on 2026-09-17 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_locationpage_country_locationpage_latitude_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Testimonial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client_name', models.CharField(max_length=120)),
                ('role', models.CharField(blank=True, help_text='e.g. "Business Owner", "Marketing Director"', max_length=150)),
                ('company_name', models.CharField(blank=True, max_length=150)),
                ('quote', models.TextField(max_length=500)),
                ('photo', models.FileField(blank=True, upload_to='testimonials/')),
                ('order', models.PositiveIntegerField(default=0)),
                ('is_published', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ('order', '-created_at'),
            },
        ),
    ]
