# Generated by Django 6.1.1 on 2026-09-19 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_testimonial'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogpost',
            name='focus_keyword',
            field=models.CharField(blank=True, help_text='The main phrase this page should rank for.', max_length=120),
        ),
        migrations.AddField(
            model_name='blogpost',
            name='og_description',
            field=models.CharField(blank=True, max_length=300, verbose_name='Social description'),
        ),
        migrations.AddField(
            model_name='blogpost',
            name='og_image',
            field=models.FileField(blank=True, upload_to='social/', verbose_name='Social image'),
        ),
        migrations.AddField(
            model_name='blogpost',
            name='og_title',
            field=models.CharField(blank=True, max_length=120, verbose_name='Social title'),
        ),
        migrations.AddField(
            model_name='blogpost',
            name='seo_canonical',
            field=models.URLField(blank=True, help_text='Only set this if the page duplicates another address.', max_length=500, verbose_name='Canonical URL'),
        ),
        migrations.AddField(
            model_name='blogpost',
            name='seo_noindex',
            field=models.BooleanField(default=False, help_text='Adds noindex and removes the page from the sitemap.', verbose_name='Hide from search engines'),
        ),
        migrations.AddField(
            model_name='blogpost',
            name='seo_score',
            field=models.PositiveSmallIntegerField(blank=True, help_text='Last score from the Studio SEO analyzer (0-100).', null=True),
        ),
        migrations.AddField(
            model_name='casestudy',
            name='focus_keyword',
            field=models.CharField(blank=True, help_text='The main phrase this page should rank for.', max_length=120),
        ),
        migrations.AddField(
            model_name='casestudy',
            name='og_description',
            field=models.CharField(blank=True, max_length=300, verbose_name='Social description'),
        ),
        migrations.AddField(
            model_name='casestudy',
            name='og_image',
            field=models.FileField(blank=True, upload_to='social/', verbose_name='Social image'),
        ),
        migrations.AddField(
            model_name='casestudy',
            name='og_title',
            field=models.CharField(blank=True, max_length=120, verbose_name='Social title'),
        ),
        migrations.AddField(
            model_name='casestudy',
            name='seo_canonical',
            field=models.URLField(blank=True, help_text='Only set this if the page duplicates another address.', max_length=500, verbose_name='Canonical URL'),
        ),
        migrations.AddField(
            model_name='casestudy',
            name='seo_noindex',
            field=models.BooleanField(default=False, help_text='Adds noindex and removes the page from the sitemap.', verbose_name='Hide from search engines'),
        ),
        migrations.AddField(
            model_name='casestudy',
            name='seo_score',
            field=models.PositiveSmallIntegerField(blank=True, help_text='Last score from the Studio SEO analyzer (0-100).', null=True),
        ),
        migrations.AddField(
            model_name='locationpage',
            name='focus_keyword',
            field=models.CharField(blank=True, help_text='The main phrase this page should rank for.', max_length=120),
        ),
        migrations.AddField(
            model_name='locationpage',
            name='og_description',
            field=models.CharField(blank=True, max_length=300, verbose_name='Social description'),
        ),
        migrations.AddField(
            model_name='locationpage',
            name='og_image',
            field=models.FileField(blank=True, upload_to='social/', verbose_name='Social image'),
        ),
        migrations.AddField(
            model_name='locationpage',
            name='og_title',
            field=models.CharField(blank=True, max_length=120, verbose_name='Social title'),
        ),
        migrations.AddField(
            model_name='locationpage',
            name='seo_canonical',
            field=models.URLField(blank=True, help_text='Only set this if the page duplicates another address.', max_length=500, verbose_name='Canonical URL'),
        ),
        migrations.AddField(
            model_name='locationpage',
            name='seo_noindex',
            field=models.BooleanField(default=False, help_text='Adds noindex and removes the page from the sitemap.', verbose_name='Hide from search engines'),
        ),
        migrations.AddField(
            model_name='locationpage',
            name='seo_score',
            field=models.PositiveSmallIntegerField(blank=True, help_text='Last score from the Studio SEO analyzer (0-100).', null=True),
        ),
        migrations.AddField(
            model_name='page',
            name='focus_keyword',
            field=models.CharField(blank=True, help_text='The main phrase this page should rank for.', max_length=120),
        ),
        migrations.AddField(
            model_name='page',
            name='og_description',
            field=models.CharField(blank=True, max_length=300, verbose_name='Social description'),
        ),
        migrations.AddField(
            model_name='page',
            name='og_image',
            field=models.FileField(blank=True, upload_to='social/', verbose_name='Social image'),
        ),
        migrations.AddField(
            model_name='page',
            name='og_title',
            field=models.CharField(blank=True, max_length=120, verbose_name='Social title'),
        ),
        migrations.AddField(
            model_name='page',
            name='seo_canonical',
            field=models.URLField(blank=True, help_text='Only set this if the page duplicates another address.', max_length=500, verbose_name='Canonical URL'),
        ),
        migrations.AddField(
            model_name='page',
            name='seo_noindex',
            field=models.BooleanField(default=False, help_text='Adds noindex and removes the page from the sitemap.', verbose_name='Hide from search engines'),
        ),
        migrations.AddField(
            model_name='page',
            name='seo_score',
            field=models.PositiveSmallIntegerField(blank=True, help_text='Last score from the Studio SEO analyzer (0-100).', null=True),
        ),
    ]
